name: dio_example
description: The example snippets for Dio.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cookie_jar:
  crypto:
  dio:
  dio_cookie_manager:
  dio_http2_adapter:

dependency_overrides:
  dio:
    path: ../dio
  dio_cookie_manager:
    path: ../plugins/cookie_manager
  dio_http2_adapter:
    path: ../plugins/http2_adapter

dev_dependencies:
  lints: any
  test: ^1.22.1
