name: dio
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 4.0.0
homepage: https://github.com/flutterchina/dio

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
  test_coverage: ^0.5.0
#  flutter_test:
#    sdk: flutter
