name: dio
version: 5.9.0

description: |
  A powerful HTTP networking package,
  supports Interceptors,
  Aborting and canceling a request,
  Custom adapters, Transformers, etc.
topics:
  - dio
  - http
  - network
  - interceptor
  - middleware
homepage: https://github.com/cfug/dio
repository: https://github.com/cfug/dio/blob/main/dio
issue_tracker: https://github.com/cfug/dio/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  async: ^2.8.2
  collection: ^1.16.0
  http_parser: ^4.0.0
  meta: ^1.5.0
  mime: '>=1.0.0 <3.0.0'
  path: ^1.8.0

  dio_web_adapter: '>=1.1.0 <3.0.0'

dev_dependencies:
  lints: any
  test: ^1.5.1
  build_runner: any
  coverage: ^1.0.3
  crypto: ^3.0.2
  mockito: ^5.2.0

  # Shared test package.
  dio_test:
    git:
      url: https://github.com/cfug/dio
      path: dio_test
