name: dio
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 4.0.5-beta1
homepage: https://github.com/flutterchina/dio

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.5.1
  coverage: ^1.0.3