name: dio2
description: A fork of a powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 5.0.0-nullsafety
homepage: https://github.com/SunnyApp/dio

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  buffer: ^1.1.0
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  test: any
  pedantic: ^1.11.0
  test_coverage: ^0.5.0
  flutter_test:
    sdk: flutter
