name: dio
version: 5.3.3

description: |
  A powerful HTTP networking package,
  supports Interceptors,
  Aborting and canceling a request,
  Custom adapters, Transformers, etc.
topics:
  - dio
  - http
  - network
  - interceptor
  - middleware
homepage: https://github.com/cfug/dio
repository: https://github.com/cfug/dio/blob/main/dio
issue_tracker: https://github.com/cfug/dio/issues

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  async: ^2.8.2
  http_parser: ^4.0.0
  meta: ^1.5.0
  path: ^1.8.0

dev_dependencies:
  lints: any
  test: ^1.5.1
  coverage: ^1.0.3
  crypto: ^3.0.2
  mockito: ^5.2.0
  build_runner: any
