name: dio_example
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 0.0.1
homepage: https://github.com/flutterchina/dio
author: wendux <824783146@qq.com>
environment:
  sdk: '>2.2.9 <3.0.0'

dependencies:
  dio:
    path: dio
  dio_http2_adapter:
    path: plugins/http2_adapter
  dio_cookie_manager:
    path: plugins/cookie_manager
  http2: ^1.0.1
  test: ^1.5.0
  test_coverage: ^0.2.0



