name: dio_test
version: 1.0.0
publish_to: none
homepage: https://github.com/cfug/dio
repository: https://github.com/cfug/dio/blob/main/dio_test
issue_tracker: https://github.com/cfug/dio/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  dio: any
  path: any

dev_dependencies:
  lints: any
  test: any
