name: source_gen_test
version: 1.0.5
description: >-
  Test support for the source_gen package.
  Includes helpers to make it easy to validate both success and failure cases.
repository: https://github.com/kevmoo/source_gen_test

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  analyzer: ^5.2.0
  build: ^2.0.0
  build_test: ^2.0.0
  dart_style: ^2.0.0
  meta: ^1.0.2
  path: ^1.3.2
  source_gen: ^1.0.0
  test: ^1.3.3

dev_dependencies:
  collection: ^1.15.0
