name: Publishable

on:
  push:
    branches:
      - main
      - '6.0.0'
    paths:
      - "**.md"
      - "**.yaml"
      - "**.yml"
  pull_request:
    branches:
      - main
      - '6.0.0'
    paths:
      - "**.md"
      - "**.yaml"
      - "**.yml"

jobs:
  publish-dry-run:
    name: Publish dry-run with packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["dio", "plugins/cookie_manager", "plugins/http2_adapter", "plugins/native_dio_adapter"]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: |
          if grep -q "flutter:" "pubspec.yaml"; then
            flutter pub get
          fi
      - run: dart pub publish --dry-run
        working-directory: ${{ matrix.directory }}
